import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

// ESLint 9 requires flat config — this repo had eslint-config-next installed
// but no config file at all (npm run lint failed outright), so lint hadn't
// actually been running. Standard `create-next-app` shape: core-web-vitals +
// the TS ruleset, via FlatCompat since eslint-config-next still ships as a
// legacy shareable config.
const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is auto-generated/regenerated by Next.js on every dev/build
    // run — never hand-edit it, so it's excluded rather than "fixed".
    ignores: [".next/**", "node_modules/**", "public/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
